### PR TITLE
feat: add osx support

### LINKED ISSUE #63: Compilation errors on OSX and Ubuntu 24.04
Currently working on my Mac (OSX) and running the build inside a docker container since it doesn't compile on OSX but compiles in `ubuntu:22.04`.

## Steps to reproduce

`docker run` one of the following:
```bash
# make builds successfully
docker run -it --platform linux/arm64 --rm ubuntu:22.04

# make doesn't compile
docker run -it --platform linux/arm64 --rm ubuntu:24.04
```

Execute inside the container
```bash
cd # go to ~
export DEBIAN_FRONTEND=noninteractive
apt update
apt install git make gcc -y
git clone --recursive https://github.com/redis/librdb
cd librdb
make
```

## Error logs for ubuntu 24.04

```bash
> make
make -C deps  all
make[1]: Entering directory '/root/librdb/deps'
make -C redis all
make[2]: Entering directory '/root/librdb/deps/redis'
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c crc64.c -o crc64.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden crc64.c > crc64.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c crcspeed.c -o crcspeed.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden crcspeed.c > crcspeed.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c endianconv.c -o endianconv.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden endianconv.c > endianconv.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c fpconv_dtoa.c -o fpconv_dtoa.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden fpconv_dtoa.c > fpconv_dtoa.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c intset.c -o intset.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden intset.c > intset.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c listpack.c -o listpack.o -g3 -DDEBUG=1
listpack.c: In function 'lpFind':
listpack.c:640:50: error: 'vll' may be used uninitialized [-Werror=maybe-uninitialized]
  640 |                 if (vencoding != UCHAR_MAX && ll == vll) {
      |                                               ~~~^~~~~~
listpack.c:608:17: note: 'vll' declared here
  608 |     int64_t ll, vll;
      |                 ^~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:15: listpack.o] Error 1
make[2]: Leaving directory '/root/librdb/deps/redis'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/root/librdb/deps'
make: *** [Makefile:26: all] Error 2
```

☝ Setting `ll` and `vll` to `int64_t ll = 0, vll = 0;` works, but we get new errors:

```bash
> make
make -C deps  all
make[1]: Entering directory '/root/librdb/deps'
make -C redis all
make[2]: Entering directory '/root/librdb/deps/redis'
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c listpack.c -o listpack.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden listpack.c > listpack.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c lzf_c.c -o lzf_c.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden lzf_c.c > lzf_c.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c lzf_d.c -o lzf_d.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden lzf_d.c > lzf_d.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c rax.c -o rax.o -g3 -DDEBUG=1
rax.c: In function 'raxIteratorAddChars':
rax.c:1280:54: error: pointer 'old' may be used after 'realloc' [-Werror=use-after-free]
 1280 |             it->key = (!old) ? it->key_static_string : old;
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
In file included from rax.c:45:
rax_malloc.h:43:21: note: call to 'realloc' here
   43 | #define rax_realloc realloc
rax.c:1278:19: note: in expansion of macro 'rax_realloc'
 1278 |         it->key = rax_realloc(old,new_max);
      |                   ^~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:15: rax.o] Error 1
make[2]: Leaving directory '/root/librdb/deps/redis'
make[1]: *** [Makefile:2: all] Error 2
make[1]: Leaving directory '/root/librdb/deps'
make: *** [Makefile:26: all] Error 2
```

Am i missing something to build on latest LTS ubuntu 24?

### Error logs for OSX
```bash
❯ make
/Library/Developer/CommandLineTools/usr/bin/make -C deps  all
/Library/Developer/CommandLineTools/usr/bin/make -C redis all
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c crc64.c -o crc64.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden crc64.c > crc64.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c crcspeed.c -o crcspeed.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden crcspeed.c > crcspeed.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c endianconv.c -o endianconv.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden endianconv.c > endianconv.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c fpconv_dtoa.c -o fpconv_dtoa.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden fpconv_dtoa.c > fpconv_dtoa.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c intset.c -o intset.o -g3 -DDEBUG=1
cc -MM -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden intset.c > intset.d
cc -fPIC -O3 -std=c99 -Wall -Wextra -pedantic -Werror -fvisibility=hidden -c listpack.c -o listpack.o -g3 -DDEBUG=1
In file included from listpack.c:45:
./listpack_malloc.h:42:10: fatal error: 'malloc.h' file not found
   42 | #include "malloc.h"
      |          ^~~~~~~~~~
1 error generated.
make[2]: *** [listpack.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by philippeboyd**
Closes #63

This adds support to build the library on OSX.

Also revamps the CI to build on multiple OS and Redis versions at the same time.

image

### CODE REVIEW

**Comment by moticless** [comment]
Hi @philippeboyd,
Thanks for the contribution! I'll review the PR over the weekend.
One quick thought: do we really need to test against 3 Ubuntu versions?

**Comment by philippeboyd** [comment]
Hi @moticless, the only reason I build against all "current" Ubuntu versions is because the version of `clang` varies depending on the distro. But if you think that's overkill, I can surely just test against the latest ubuntu only. Let me know :)

### 20.04
```
clang version 10.0.0-4ubuntu1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### 22.04
```
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### 24.04
```
Ubuntu clang version 18.1.3 (1ubuntu1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by moticless** [comment]
I think it’s redundant unless we bumped into a specific issue around it. More importantly, it seems GCC is no longer implicitly tested in the 'build' job as it was before.

File: deps/redis/listpack_malloc.h [hunk 1]
```diff
@@ -39,12 +39,24 @@
 #ifndef LISTPACK_ALLOC_H
 #define LISTPACK_ALLOC_H
 //#include "zmalloc.h"
+
+#ifdef __APPLE__
+#include <malloc/malloc.h>
+#else
 #include "malloc.h"
+#endif
```
Comment (moticless) [inline deps/redis/listpack_malloc.h:47]: Maybe instead we can use portable `#include <stdlib.h>`

File: deps/redis/listpack_malloc.h [hunk 2]
```diff
@@ -39,12 +39,24 @@
...
+
 /* We use zmalloc_usable/zrealloc_usable instead of zmalloc/zrealloc
  * to ensure the safe invocation of 'zmalloc_usable_size().
  * See comment in zmalloc_usable_size(). */
```
Comment (moticless) [inline deps/redis/listpack_malloc.h:51]: This comment is no longer relevant. Please remove it.

File: test/Makefile [hunk 3]
```diff
@@ -37,7 +46,13 @@ $(TARGET_TEST): $(OBJECTS)
 	$(CC) $(OBJECTS) -o $@ $(DEBUG) $(CFLAGS) $(LIBS)
 
 $(TARGET_TEST_STATIC): $(OBJECTS)
-	$(CC) $(OBJECTS) -o $@ $(DEBUG) $(CFLAGS) $(LIBS) $(LIBS_STATIC)
+ifeq ($(uname_S),Darwin)
+	@echo "***********************************************************************"
+	@echo "Skipping $(TARGET_TEST_STATIC) on OSX due to a complex compilation bug."
+	@echo "***********************************************************************"
```
Comment (moticless) [inline test/Makefile:52]: What is this complex compilation bug? If it is something known, maybe provide a link with the comment.
Otherwise maybe assist chatgpt to resolve it or write current status of this issue for the next one to tackle it

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -8,96 +8,66 @@ on:
...
+          - "ubuntu-20.04"
+          - "ubuntu-22.04"
+          - "ubuntu-24.04"
+        version:
+          - "5.0"
+          - "6.0"
+          - "6.2"
+          - "7.2"
+          - "7.4"
+          - "unstable"
```
[the remark this answers is not in the document]
Comment (philippeboyd) [reply .github/workflows/ci.yml:24]: Sorry for late replies, I was pretty busy these last few days.

I find the benefit is to show that the library can build under any OS and with any compiler (I'll add back `gcc`). Might be overkill but at least we cover all grounds since `gcc` and `clang` versions vary between OS instead of building randomly on either with `gcc` or `clang`. Let me know what you think.

## Ubuntu 20.04
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

clang version 10.0.0-4ubuntu1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

## Ubuntu 22.04
```
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Ubuntu clang version 14.0.0-1ubuntu1.1
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

## Ubuntu 24.04
```
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Ubuntu clang version 18.1.3 (1ubuntu1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

What do you think?

File: src/ext/Makefile [hunk 5]
```diff
@@ -32,14 +32,24 @@ LDFLAGS  =
...
+endif
+
+# Platform-specific overrides
+uname_S := $(shell sh -c 'uname -s 2>/dev/null || echo not')
+
+ifeq ($(uname_S),Darwin)
+	SONAME_ARG = -install_name
+else
+	SONAME_ARG = -soname
 endif
```
[the remark this answers is not in the document]
Comment (philippeboyd) [reply src/ext/Makefile:45]: Good idea! I'll add that. Weird because I didn't get any error when building on OSX with `-shared`. 🤔

File: deps/redis/listpack_malloc.h (hunk 2 above)
Comment (philippeboyd) [reply deps/redis/listpack_malloc.h:51]: Will do!

File: deps/redis/listpack_malloc.h (hunk 1 above)
Comment (philippeboyd) [reply deps/redis/listpack_malloc.h]: I tried adding only `#include <stdlib.h>` but that does't work on OSX.

```bash
listpack.c:176:16: error: call to undeclared function 'malloc_usable_size'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  176 |     if (size < lp_malloc_size(lp)) {
      |                ^
./listpack_malloc.h:57:24: note: expanded from macro 'lp_malloc_size'
   57 | #define lp_malloc_size malloc_usable_size
      |                        ^
listpack.c:176:14: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
  176 |     if (size < lp_malloc_size(lp)) {
      |         ~~~~ ^ ~~~~~~~~~~~~~~~~~~
listpack.c:771:30: error: call to undeclared function 'malloc_usable_size'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  771 |         new_listpack_bytes > lp_malloc_size(lp)) {
      |                              ^
./listpack_malloc.h:57:24: note: expanded from macro 'lp_malloc_size'
   57 | #define lp_malloc_size malloc_usable_size
      |                        ^
listpack.c:771:28: warning: comparison of integers of different signs: 'uint64_t' (aka 'unsigned long long') and 'int' [-Wsign-compare]
  771 |         new_listpack_bytes > lp_malloc_size(lp)) {
      |         ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
make[2]: *** [listpack.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

or even 

```bash
listpack.c:176:16: error: call to undeclared function 'malloc_size'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  176 |     if (size < lp_malloc_size(lp)) {
      |                ^
./listpack_malloc.h:55:24: note: expanded from macro 'lp_malloc_size'
   55 | #define lp_malloc_size malloc_size
      |                        ^
listpack.c:176:14: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
  176 |     if (size < lp_malloc_size(lp)) {
      |         ~~~~ ^ ~~~~~~~~~~~~~~~~~~
listpack.c:771:30: error: call to undeclared function 'malloc_size'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  771 |         new_listpack_bytes > lp_malloc_size(lp)) {
      |                              ^
./listpack_malloc.h:55:24: note: expanded from macro 'lp_malloc_size'
   55 | #define lp_malloc_size malloc_size
      |                        ^
listpack.c:771:28: warning: comparison of integers of different signs: 'uint64_t' (aka 'unsigned long long') and 'int' [-Wsign-compare]
  771 |         new_listpack_bytes > lp_malloc_size(lp)) {
      |         ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
make[2]: *** [listpack.o] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

with 
```c
#ifdef __APPLE__
#define lp_malloc_size malloc_size
#else
#define lp_malloc_size malloc_usable_size
#endif
```

File: test/Makefile (hunk 3 above)
Comment (philippeboyd) [reply test/Makefile:52]: Issue with the linker, not sure where to go from there... I was able to fix for dynamic by tweaking the compiler flags but can't make it work for static.

```bash
ld: library ':librdb-ext.a' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test_static_lib] Error 1
make: *** [build_test] Error 2
```

Comment (philippeboyd) [reply test/Makefile]: I fixed it, let me know if it makes sense (PR updated)

File: .github/workflows/ci.yml (hunk 4 above)
[the remark this answers is not in the document]
Comment (moticless) [reply .github/workflows/ci.yml]: No worries, I am also a bit delayed in replying. 

I see your point about covering all grounds, and I agree. Sticking to ubuntu-latest for now makes sense.

File: deps/redis/listpack_malloc.h (hunk 1 above)
Comment (moticless) [reply deps/redis/listpack_malloc.h]: Ok. Let's leave it. That works for now.

File: test/Makefile (hunk 3 above)
Comment (moticless) [reply test/Makefile]: I am not sure to which change to relate it.

**Review by moticless — APPROVED** [review]

**Comment by moticless** [comment]
Hey @philippeboyd, 
is everything set with this PR?

File: test/Makefile (hunk 3 above)
Comment (philippeboyd) [reply test/Makefile]: Oh sorry, it was with the way `LIBS_STATIC` was set in the test. I wasn't able to build for static on OSX.
https://github.com/redis/librdb/pull/65/files#diff-740cb5a1689091cb894445e46683c255e39689ccba1c6c63d8a8841c8df8817dR25

**Comment by philippeboyd** [comment]
> Hey @philippeboyd, is everything set with this PR?

Yes, the CI github action looks good and tests everything on Linux and OSX :+1: I think we can go from here!
